baseURL = 'https://thenightshadenotebook.com'
languageCode = 'en-us'
title = 'The Night Shade Notebook'

defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
