baseURL = "thenightshadenotebook.com/"
languageCode = "en-us"
title = "The Nightshade Notebook"
enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
